server:
  port: 8080

spring:
  application:
    name: book-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://commercebank.c986wiuwap7e.us-east-1.rds.amazonaws.com:3306/commercebankprojectdb
    username: admin
    password: MAR123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true